export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  darkText: true,
  topLine: "? true : false",
  headline: "Why React is awesome?",
  description: "Try it",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "React",
  dark: true,
  primary: true,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  darkText: false,
  topLine: "Wooo001W",
  headline: "Curiosity is the fuel for discovery, inquiry and learning.",
  description: "Try it",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-2.svg"),
  alt: "React",
  dark: false,
  primary: true,
};

export const homeObjThree = {
  id: "services",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "Join our team",
  headline: "It is essential to be a part of a successful team",
  description: "Woooow",
  buttonLabel: "Apply",
  imgStart: true,
  img: require("../../images/svg-3.svg"),
  alt: "React",
  dark: true,
  primary: true,
  darkText: true,
};
